### ISSUE TITLE
About the ”length_norm_coeff“

### ISSUE THREAD

**Issue by c-box** [dmis-lab/BioLAMA#2]
Hi, very interesting work. 
I notice that you set the default ”length_norm_coeff“ as 0, wouldn't it affect the decoding results? e.g., prefer the longer span?
```python
# length norm
length_norm_coeff = 0.0
lp = np.power(mask_len,length_norm_coeff)
prob = np.exp(log_prob / lp) 
```

**Comment by mjeensung** [comment]
Hi, I'm sorry for the late reply.

Actually, the sum of log probabilities favors shorter predictions.

When you set **length_norm_coeff** to 0, **lp** (i.e., length penalty) will be always 1, and this will change nothing on the final probability.
On the other hand, when you set **length_norm_coeff** to 1, **lp** will be the number of masks, and this will normalize the final prediction not to favor the shorter length.

We've performed hyperparameter searching for the best **length_norm_coeff** (e.g., 0, 0.2, 0.4, ..., 1.0), and observed the final score is the best when **length_norm_coeff** is set to 0.
That's why I set the default **length_norm_coeff** to 0.

I'll make sure to clarify this by adding more comments.
Thank you for asking!

**Comment by c-box** [comment]
Yes, that's really helpful, thank you very much!
